const constants = {
    GET_BREEDS: 'GET_BREEDS',
    GET_BREEDS_REQUEST: 'GET_BREEDS_REQUEST',
    GET_BREEDS_SUCCESS: 'GET_BREEDS_SUCCESS',
    GET_BREEDS_FAIL: 'GET_BREEDS_FAIL',
    SET_BREED: 'SET_BREED'
};

export default constants;