const constants = {
    GET_BREEDS_REQUEST: 'GET_BREEDS_REQUEST',
    GET_BREEDS_SUCCESS: 'GET_BREEDS_SUCCESS',
    GET_BREEDS_FAIL: 'GET_BREEDS_FAIL',
    SET_BREED_REQUEST: 'SET_BREED_REQUEST',
    SET_BREED_SUCCESS: 'SET_BREED_SUCCESS',
    SET_BREED_FAIL: 'SET_BREED_FAIL'
};

export default constants;